### ISSUE TITLE
Deploy 1.3.18 to Maven Central

### ISSUE THREAD

**Issue by reftel** [mtakaki/dropwizard-hikaricp#13]
Hi,

there seems to be a 1.3.18 release, but the latest for 1.3.x. on Maven Central is still 1.3.8 (see https://search.maven.org/artifact/com.github.mtakaki/dropwizard-hikaricp ). Could you please upload 1.3.18?

**Comment by reftel** [comment]
1.3.29 is now available (even though neither of the web pages of search.maven.org and mvnrepository.com show it yet). Thanks!

**Comment by mtakaki** [comment]
Great! Thanks for the update!
