### ISSUE TITLE
Signature of DataSourceFactory.setAutoCommitByDefault differs form dropwizard-db

### ISSUE THREAD

**Issue by reftel** [mtakaki/dropwizard-hikaricp#14]
In dropwizard-hikaricp, `DataSourceFactory.setAutoCommitByDefault` takes an `Optional<Boolean>`:
https://github.com/mtakaki/dropwizard-hikaricp/blob/1.3.x/src/main/java/io/dropwizard/db/DataSourceFactory.java#L325
In dropwizard-db, the same method takes a plain Boolean:
https://github.com/dropwizard/dropwizard/blob/release/1.3.x/dropwizard-db/src/main/java/io/dropwizard/db/DataSourceFactory.java#L635
This results in odd-looking errors at runtime if one happens to unintentionally pull in dropwizard-db transitively at compile time, but use DataSourceFactory from dropwizard-hikaricp at run time.

**Comment by mtakaki** [comment]
Ahhh, good catch! Lemme fix that.

**Comment by mtakaki** [comment]
This is fixed on version 1.3.29. Thanks for reporting it!
